apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
spec:
  params:
  - name: url
    type: string 
  - name: branch
    type: string
    default: "main"
  workspaces:
  - name: output
  steps:
  - name: echo
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo $(params.branch)
      echo "$(params.url)" >> $(workspaces.output.path)/file
      echo "commit-sha: 1234" >>$(results.commit.path)
  results:
  - name: commit
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-greeting-read-workspace
spec:
  params:
  - name: greeting
    type: string
  workspaces:
  - name: input
  steps:
  - name: echo
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "$(params.greeting)"
      ls $(workspaces.input.path)
---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-with-taskrefs
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 5m
      params:
      - name: git-url
        value: "https://github.com/tektoncd/pipeline"
      workspaces:
      - name: source-code
        emptyDir: {}
      pipelineSpec:
        workspaces:
        - name: source-code
        tasks:
        - name: clone-repo
          params:
          - name: url
            value: $(params.git-url)
          taskRef:
            name: clone
          workspaces:
          - name: output
            workspace: source-code
        - name: echo-good-afternoon
          params:
          - name: greeting
            value: "Good Afternoon!"
          taskRef:
            name: echo-greeting-read-workspace
          workspaces:
          - name: input
            workspace: source-code
          runAfter:
          - clone-repo
        - name: echo-good-morning
          params:
          - name: greeting
            value: "Good Morning!"
          taskRef:
            name: echo-greeting-read-workspace
          workspaces:
          - name: input
            workspace: source-code
          runAfter:
          - clone-repo
