apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-run
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 5m
      params:
      - name: git-url
        value: "https://github.com/tektoncd/pipeline"
      workspaces:
      - name: source-code
        emptyDir: {}
      pipelineSpec:
        params:
        - name: git-url
          type: string
        - name: branch
          type: string
          default: "main"
        tasks:
        - name: clone
          params:
          - name: url
            value: $(params.git-url)
          - name: branch
            value: $(params.branch)
          taskSpec:
            workspaces:
            - name: output
            results:
            - name: commit
            steps:
              - name: git-clone
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo $(params.branch)
                  echo "$(params.url)" >> $(workspaces.output.path)/file
                  echo "commit-sha: 1234" >> $(results.commit.path)
          workspaces:
          - name: output
            workspace: source-code
        - name: read-git-output
          taskSpec:
            steps:
              - name: echo2
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  cat $(workspaces.input.path)/file
            workspaces:
            - name: input
          workspaces:
          - name: input
            workspace: source-code
          runAfter:
          - clone
        - name: echo-good-morning
          taskSpec:
            steps:
              - name: echo2
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "Good Morning!"
          runAfter:
          - clone
         
