apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: good-morning-good-afternoon
spec:
  workspaces:
  - name: source-code
  params:
  - name: git-url
  - name: branch
    default: "main"
  tasks:
  - name: clone
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: $(params.git-url)
    - name: branch
      value: $(params.branch)
    taskSpec:
      steps:
      - name: clone
        image: ubuntu
        script: |
          #!/usr/bin/env bash
          echo "$(params.url):$(params.branch)" >> $(workspaces.output.path)
          echo "commit-sha: 1234" >>$(results.commit.path)
      workspaces:
      - name: output
      params:
      - name: url
        type: string
      - name: branch
        type: string
      results:
      - name: commit
  - name: echo-good-afternoon
    taskSpec:
      steps:
      - name: echo2
        image: ubuntu
        script: |
          #!/usr/bin/env bash
          echo "Good Afternoon!s"
    runAfter:
    - clone
  - name: echo-good-morning
    taskSpec:
      steps:
      - name: echo2
        image: ubuntu
        script: |
          #!/usr/bin/env bash
          echo "Good Morning!"
    runAfter:
    - clone
---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-with-pipelineref
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 5m
      workspaces:
      - name: source-code
        emptyDir: {}
      params:
      - name: git-url
        value: "https://github.com/tektoncd/pipeline"
      pipelineRef:
        name: good-morning-good-afternoon