apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  workspaces:
  - name: source-code
  results:
  - name: digest
  steps:
  - name: build
    image: "gcr.io/kaniko-project/executor:v1.5.1"
    args: [
      "--dockerfile=$(workspaces.source-code.path)/Dockerfile",
      "--context=dir://$(workspaces.source-code.path)",
      "--digest-file=$(results.digest.path)",
      "--no-push",
    ]
---
apiVersion: workflows.tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: build-on-branch-push
spec:
  triggers:
  - name: on-pr
    event:
      type: "push"
      secret:
        secretName: "webhook-secret"
        secretKey: "token"
    filters:
      gitRef:
        regex: "^main$"
    bindings:
    - name: commit-sha
      value: $(body.pull_request.head.sha)
    - name: url
      value: $(body.repository.clone_url)
  params:
  - name: url
    default: "https://github.com/lbernick/web-app-demo"
  - name: commit-sha
    default: main
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
          bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.7
        params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: $(params.commit-sha)
        workspaces:
        - name: "output"
          workspace: "source"
      - name: kaniko-build
        runAfter: [ "fetch-source" ]
        workspaces:
        - name: "source"
          workspace: "source"
        taskRef:
          name: kaniko-build