apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-test
spec:
  workspaces:
  - name: source
  steps:
  - name: test
    image: python
    workingDir: $(workspaces.source.path)
    args: [
      "python",
      "-m",
      "src.animals_test",
    ]
---
apiVersion: workflows.tekton.dev/v1alpha1
kind: GitRepository
metadata:
  name: webapp
  namespace: ops
spec:
  url: https://github.com/lbernick/web-app-demo
  webhookSecret:
    name: githubsecret
    key: secretToken
  accessToken:
    name: githubsecret
    key: accessToken
---
apiVersion: workflows.tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: ci-workflow
spec:
  repos:
  - name: webapp
  triggers:
  - event:
      source:
        repo: webapp
      types: ["pull-request"]
    filters:
      gitRef:
        regex: '^main$'
  params:
  - name: url
    default: $(repos.webapp.url)
  - name: commit-sha
    default: main
  pipelineSpec:
    tasks:
      - name: clone
        taskRef:
          name: git-clone
          bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.7
        workspaces:
        - name: output
          workspace: source
        params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.commit-sha)
      - name: unit-tests
        taskRef:
          name: python-test
        runAfter: ["clone"]
        workspaces:
        - name: source
          workspace: source
