apiVersion: tekton.dev/v1alpha1
kind: GitRepository
metadata:
  name: git-repo
spec:
  url: https://github.com/lbernick/web-app-demo
  connector: github-webhook
  customFields:
    accessToken:
      secretKeyRef:
        name: knative-githubsecret
        key: accessToken
    secretToken:
      secretKeyRef:
        name: knative-githubsecret
        key: secretToken
---
apiVersion: tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: example-workflow
spec:
  repos:
  - name: git-repo
  triggers:
  - event:
      source:
        repo: git-repo
      type: pull_request
    filters:
      gitRef:
        regex: '^main$'
  pipelineSpec:
    tasks:
      - name: clone
        taskRef:
          name: git-clone
          bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.7
        workspaces:
        - name: output
          workspace: source
        params:
        - name: url
          value: 
        - name: revision
          value: $(params.revision)
      - name: unit-tests
        taskSpec:
          steps:
          - image: busybox
            script: echo "hello"